---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: clean the maven project
      shell: mvn clean
      args:
        chdir: ..


- hosts: all
  remote_user: ec2-user
  tasks:
    - name: install java, maven, nc, pip
      become: yes
      yum:
        name:
          - java-devel
          - maven
          - nc
          - python-pip

    - name: copy project files to servers
      become: no
      copy:
        src: "../"
        dest: "/home/ec2-user/threads-and-events"

    - name: build the project
      become: no
      shell: mvn package -DskipTests
      args:
        chdir: /home/ec2-user/threads-and-events


